[project]
name = "hello-py"
version = "0.0.1"
description = "Hello World for Python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.13",
    "codetiming>=1.4.0",
    "requests>=2.32.4",
]
